### ISSUE TITLE
Crash onBackPressed

### ISSUE THREAD

**Issue by kreativityapps** [pollfish/flutter-plugin-pollfish#16]
Using flutter_pollfish 4.0.7 several crash reports can be seen in crashlytics.
It occurs on Android 8, 9, 10, 11.
Couldn't reproduce it locally yet, I hope the logs help.

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void t8.p1.n()' on a null object reference
       at com.pollfish.internal.PollfishOverlayActivity.onBackPressed(PollfishOverlayActivity.java:5)
       at android.app.Activity.onKeyUp(Activity.java:3645)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3969)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:387)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5454)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5322)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4829)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4882)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4848)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4988)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4856)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5045)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4829)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4882)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4848)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4856)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4829)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4882)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4848)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5021)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5182)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3064)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2607)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2598)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3041)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:343)
       at android.os.Looper.loop(Looper.java:188)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by fotism23** [comment]
Hello @kreativityapps 

We have released version 4.0.8 which hopefully fixes the issue you are experiencing, since we were unable to reproduce it locally as well.

Please upgrade to the latest version and let us know of the outcome.

Thanks

**Comment by kreativityapps** [comment]
Thank you, much appreciated.

**Comment by kreativityapps** [comment]
Thank you, tried with the new version, no more crashes with this.
