### ISSUE TITLE
Crash on No WebView installed

### ISSUE THREAD

**Issue by kreativityapps** [pollfish/flutter-plugin-pollfish#19]
On some Android 12 and 13, Samsung devices using `flutter_pollfish 4.2.0` in crash logs I can see the following:
```
Fatal Exception: android.util.AndroidRuntimeException: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:382)
       at android.webkit.WebView.getFactory(WebView.java:2599)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2593)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2661)
       at android.view.View.<init>(View.java:5648)
       at android.view.View.<init>(View.java:5823)
       at android.view.ViewGroup.<init>(ViewGroup.java:707)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:59)
       at android.webkit.WebView.<init>(WebView.java:426)
       at android.webkit.WebView.<init>(WebView.java:368)
       at android.webkit.WebView.<init>(WebView.java:350)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:327)
       at com.pollfish.internal.c4.<init>(c4.java:1)
       at com.pollfish.internal.t5.c(t5.java:1)
       at com.pollfish.internal.u5.invoke(u5.java:1)
       at com.pollfish.internal.c0.a(c0.java:1)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by fotism23** [comment]
Thanks for the report @kreativityapps
